name: Report a bug
description: Share when something isn't working as expected
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share a bug report!
  - type: textarea
    attributes:
      label: Bug description
      description: Share a clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducing the issue
      description: Provide a minimal, reproducible example.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expectations vs. reality
      description: Give a clear description of what you expected to happen.
  - type: input
    attributes:
      label: Affected version(s)
      description: Share the version(s) where you observed this bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
