name: Repo configuration

on:
  workflow_dispatch:

permissions: {}

jobs:
  labels:
    name: Sync labels

    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          sparse-checkout: .github/labels.yml

      - uses: EndBug/label-sync@52074158190acb45f3077f9099fea818aa43f97a # v2.3.3
        with:
          config-file: |
            https://raw.githubusercontent.com/bsoyka/cookiecutters/main/python-library/default-labels.yaml
            .github/labels.yaml
